[workspace]
members = [
  "apps/runtime-host",
  "core/capability",
  "core/config",
  "core/contracts",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "UNLICENSED"
publish = false
version = "0.0.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
