// @generated by tools/scripts/contracts.mjs from core/contracts/version.json, core/contracts/error-codes.json, and core/contracts/runtime-message-v1.json.
// Do not edit manually; run `pnpm contracts:generate`.

#pragma once

#include <cstdint>
#include <optional>
#include <string_view>

namespace ai_voice::contracts {

inline constexpr std::uint32_t kContractSchemaVersion = 1U;
inline constexpr std::uint32_t kErrorCodeSchemaVersion = 1U;
inline constexpr std::string_view kRuntimeVersion = "0.0.0";
inline constexpr std::uint32_t kIpcProtocolCurrentVersion = 1U;
inline constexpr std::uint32_t kIpcProtocolMinimumCompatibleVersion = 1U;
inline constexpr std::uint32_t kVoiceEngineAbiV1Version = 1U;
inline constexpr std::uint32_t kVoiceEngineAbiCurrentVersion = 1U;
inline constexpr std::uint32_t kVoiceEngineAbiMinimumCompatibleVersion = 1U;

constexpr bool is_ipc_protocol_compatible(std::uint32_t version) {
  return version >= kIpcProtocolMinimumCompatibleVersion && version <= kIpcProtocolCurrentVersion;
}

constexpr bool is_voice_engine_abi_compatible(std::uint32_t version) {
  return version >= kVoiceEngineAbiMinimumCompatibleVersion && version <= kVoiceEngineAbiCurrentVersion;
}

enum class ErrorCode : std::int32_t {
  Success = 0,
  UnsupportedProtocolVersion = 1000,
  UnsupportedVoiceEngineAbi = 1001,
  MalformedFrame = 1100,
  FrameTooLarge = 1101,
  RuntimeUnavailable = 1200,
  RuntimeShuttingDown = 1201,
  EngineUnavailable = 1300,
  InvalidArgument = 1301,
  InvalidState = 1302,
  BufferTooSmall = 1303,
  InternalError = 1900,
};

enum class ErrorCategory {
  Success,
  Version,
  Framing,
  Runtime,
  Engine,
  Internal,
};

constexpr std::int32_t error_code_value(ErrorCode code) {
  return static_cast<std::int32_t>(code);
}

constexpr std::optional<ErrorCode> error_code_from_value(std::int32_t value) {
  switch (value) {
    case 0: return ErrorCode::Success;
    case 1000: return ErrorCode::UnsupportedProtocolVersion;
    case 1001: return ErrorCode::UnsupportedVoiceEngineAbi;
    case 1100: return ErrorCode::MalformedFrame;
    case 1101: return ErrorCode::FrameTooLarge;
    case 1200: return ErrorCode::RuntimeUnavailable;
    case 1201: return ErrorCode::RuntimeShuttingDown;
    case 1300: return ErrorCode::EngineUnavailable;
    case 1301: return ErrorCode::InvalidArgument;
    case 1302: return ErrorCode::InvalidState;
    case 1303: return ErrorCode::BufferTooSmall;
    case 1900: return ErrorCode::InternalError;
    default: return std::nullopt;
  }
}

constexpr ErrorCategory error_code_category(ErrorCode code) {
  switch (code) {
    case ErrorCode::Success: return ErrorCategory::Success;
    case ErrorCode::UnsupportedProtocolVersion: return ErrorCategory::Version;
    case ErrorCode::UnsupportedVoiceEngineAbi: return ErrorCategory::Version;
    case ErrorCode::MalformedFrame: return ErrorCategory::Framing;
    case ErrorCode::FrameTooLarge: return ErrorCategory::Framing;
    case ErrorCode::RuntimeUnavailable: return ErrorCategory::Runtime;
    case ErrorCode::RuntimeShuttingDown: return ErrorCategory::Runtime;
    case ErrorCode::EngineUnavailable: return ErrorCategory::Engine;
    case ErrorCode::InvalidArgument: return ErrorCategory::Engine;
    case ErrorCode::InvalidState: return ErrorCategory::Engine;
    case ErrorCode::BufferTooSmall: return ErrorCategory::Engine;
    case ErrorCode::InternalError: return ErrorCategory::Internal;
  }
  return ErrorCategory::Internal;
}

}  // namespace ai_voice::contracts
