// @generated by tools/scripts/contracts.mjs from core/contracts/version.json, core/contracts/error-codes.json, and core/contracts/runtime-message-v1.json.
// Do not edit manually; run `pnpm contracts:generate`.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>

namespace ai_voice::contracts::runtime_message {

inline constexpr std::uint32_t kRuntimeMessageSchemaVersion = 1U;
inline constexpr std::array<std::uint8_t, 4> kMagic{'A', 'V', 'R', 'M'};
inline constexpr std::uint16_t kWireVersion = 1U;
inline constexpr std::size_t kHeaderSize = 32U;
inline constexpr std::size_t kMaxControlPayloadBytes = 65536U;
inline constexpr std::size_t kMaxFrameBytes = 65568U;
inline constexpr std::size_t kMaxHelloPayloadBytes = 1024U;
inline constexpr std::size_t kMaxErrorPayloadBytes = 4096U;
inline constexpr std::size_t kMaxPingPayloadBytes = 256U;

enum class MessageKind : std::uint8_t {
  Hello = 1,
  Request = 2,
  Response = 3,
};

constexpr std::optional<MessageKind> message_kind_from_value(std::uint8_t value) {
  switch (value) {
    case 1: return MessageKind::Hello;
    case 2: return MessageKind::Request;
    case 3: return MessageKind::Response;
    default: return std::nullopt;
  }
}

enum class Command : std::uint16_t {
  None = 0,
  Ping = 1,
  GetCapabilities = 2,
  RunMockPipeline = 3,
  Shutdown = 4,
};

constexpr std::optional<Command> command_from_value(std::uint16_t value) {
  switch (value) {
    case 0: return Command::None;
    case 1: return Command::Ping;
    case 2: return Command::GetCapabilities;
    case 3: return Command::RunMockPipeline;
    case 4: return Command::Shutdown;
    default: return std::nullopt;
  }
}

}  // namespace ai_voice::contracts::runtime_message
