if(NOT DEFINED SOURCE)
  message(FATAL_ERROR "Mock source path is required")
endif()

file(READ "${SOURCE}" source)
string(FIND "${source}" "mock_process_audio(" begin)
string(FIND "${source}" "mock_reset(" end)
if(begin EQUAL -1 OR end EQUAL -1 OR end LESS_EQUAL begin)
  message(FATAL_ERROR "Could not isolate Mock process_audio hot path")
endif()
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${source}" ${begin} ${length} process_audio)

foreach(forbidden IN ITEMS "spdlog" "log(" "fprintf" "printf" "std::cerr" "std::cout")
  string(FIND "${process_audio}" "${forbidden}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "Mock process_audio contains forbidden logging token: ${forbidden}")
  endif()
endforeach()

foreach(required IN ITEMS "process_call_count.fetch_add" "input_frame_count.fetch_add" "output_frame_count.fetch_add")
  string(FIND "${process_audio}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Mock process_audio lost atomic-only metric update: ${required}")
  endif()
endforeach()
