// @generated by tools/scripts/contracts.mjs from core/contracts/version.json and core/contracts/error-codes.json.
// Do not edit manually; run `pnpm contracts:generate`.

pub const CONTRACT_SCHEMA_VERSION: u32 = 1;
pub const ERROR_CODE_SCHEMA_VERSION: u32 = 1;
pub const RUNTIME_VERSION: &str = "0.0.0";
pub const IPC_PROTOCOL_CURRENT_VERSION: u32 = 1;
pub const IPC_PROTOCOL_MINIMUM_COMPATIBLE_VERSION: u32 = 1;
pub const VOICE_ENGINE_ABI_CURRENT_VERSION: u32 = 1;
pub const VOICE_ENGINE_ABI_MINIMUM_COMPATIBLE_VERSION: u32 = 1;

pub const fn is_ipc_protocol_compatible(version: u32) -> bool {
    version >= IPC_PROTOCOL_MINIMUM_COMPATIBLE_VERSION && version <= IPC_PROTOCOL_CURRENT_VERSION
}

pub const fn is_voice_engine_abi_compatible(version: u32) -> bool {
    version >= VOICE_ENGINE_ABI_MINIMUM_COMPATIBLE_VERSION
        && version <= VOICE_ENGINE_ABI_CURRENT_VERSION
}

#[repr(i32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ErrorCode {
    Success = 0,
    UnsupportedProtocolVersion = 1000,
    UnsupportedVoiceEngineAbi = 1001,
    MalformedFrame = 1100,
    FrameTooLarge = 1101,
    RuntimeUnavailable = 1200,
    RuntimeShuttingDown = 1201,
    EngineUnavailable = 1300,
    InvalidArgument = 1301,
    InvalidState = 1302,
    BufferTooSmall = 1303,
    InternalError = 1900,
}

impl ErrorCode {
    pub const fn value(self) -> i32 {
        self as i32
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ErrorCategory {
    Success,
    Version,
    Framing,
    Runtime,
    Engine,
    Internal,
}

pub const fn error_code_from_value(value: i32) -> Option<ErrorCode> {
    match value {
        0 => Some(ErrorCode::Success),
        1000 => Some(ErrorCode::UnsupportedProtocolVersion),
        1001 => Some(ErrorCode::UnsupportedVoiceEngineAbi),
        1100 => Some(ErrorCode::MalformedFrame),
        1101 => Some(ErrorCode::FrameTooLarge),
        1200 => Some(ErrorCode::RuntimeUnavailable),
        1201 => Some(ErrorCode::RuntimeShuttingDown),
        1300 => Some(ErrorCode::EngineUnavailable),
        1301 => Some(ErrorCode::InvalidArgument),
        1302 => Some(ErrorCode::InvalidState),
        1303 => Some(ErrorCode::BufferTooSmall),
        1900 => Some(ErrorCode::InternalError),
        _ => None,
    }
}

pub const fn error_code_category(code: ErrorCode) -> ErrorCategory {
    match code {
        ErrorCode::Success => ErrorCategory::Success,
        ErrorCode::UnsupportedProtocolVersion => ErrorCategory::Version,
        ErrorCode::UnsupportedVoiceEngineAbi => ErrorCategory::Version,
        ErrorCode::MalformedFrame => ErrorCategory::Framing,
        ErrorCode::FrameTooLarge => ErrorCategory::Framing,
        ErrorCode::RuntimeUnavailable => ErrorCategory::Runtime,
        ErrorCode::RuntimeShuttingDown => ErrorCategory::Runtime,
        ErrorCode::EngineUnavailable => ErrorCategory::Engine,
        ErrorCode::InvalidArgument => ErrorCategory::Engine,
        ErrorCode::InvalidState => ErrorCategory::Engine,
        ErrorCode::BufferTooSmall => ErrorCategory::Engine,
        ErrorCode::InternalError => ErrorCategory::Internal,
    }
}
