// @generated by tools/scripts/contracts.mjs from core/contracts/version.json, core/contracts/error-codes.json, and core/contracts/runtime-message-v1.json.
// Do not edit manually; run `pnpm contracts:generate`.

pub const RUNTIME_MESSAGE_SCHEMA_VERSION: u32 = 1;
pub const MAGIC: [u8; 4] = *b"AVRM";
pub const WIRE_VERSION: u16 = 1;
pub const HEADER_SIZE: usize = 32;
pub const MAX_CONTROL_PAYLOAD_BYTES: usize = 65536;
pub const MAX_FRAME_BYTES: usize = 65568;
pub const MAX_HELLO_PAYLOAD_BYTES: usize = 1024;
pub const MAX_ERROR_PAYLOAD_BYTES: usize = 4096;
pub const MAX_PING_PAYLOAD_BYTES: usize = 256;

#[repr(u8)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MessageKind {
    Hello = 1,
    Request = 2,
    Response = 3,
}

pub const fn message_kind_from_value(value: u8) -> Option<MessageKind> {
    match value {
        1 => Some(MessageKind::Hello),
        2 => Some(MessageKind::Request),
        3 => Some(MessageKind::Response),
        _ => None,
    }
}

#[repr(u16)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Command {
    None = 0,
    Ping = 1,
    GetCapabilities = 2,
    RunMockPipeline = 3,
    Shutdown = 4,
}

pub const fn command_from_value(value: u16) -> Option<Command> {
    match value {
        0 => Some(Command::None),
        1 => Some(Command::Ping),
        2 => Some(Command::GetCapabilities),
        3 => Some(Command::RunMockPipeline),
        4 => Some(Command::Shutdown),
        _ => None,
    }
}
